[workspace]
resolver = "2"

members = ["pudcli", "pudlib", "puds", "pudw"]

[workspace.dependencies]
actix = "0.13.5"
actix-codec = "0.5.2"
actix-http = "3.6.0"
actix-rt = "2.9.0"
anyhow = "1.0.81"
awc = { version = "3.4.0", default-features = false, features = [
    "compress-brotli",
    "rustls-0_21",
] }
bincode = "1.3.3"
bytes = "1.6.0"
clap = { version = "4.5.4", features = ["derive"] }
futures = "0.3.30"
getset = "0.1.2"
lazy_static = "1.4.0"
regex = "1.10.4"
rustversion = "1.0.15"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
time = "0.3.34"
tokio = { version = "1.37.0", features = ["sync"] }
tracing = { version = "0.1.40", features = [
  "max_level_trace",
  "release_max_level_info",
] }
typed-builder = "0.18.1"
uuid = { version = "1.8.0", features = ["v4", "serde"] }
vergen-gix = { version = "1.0.0-beta.2", features = [
  "build",
  "cargo",
  "rustc",
  "si",
] }
