[workspace]
resolver = "2"

members = ["pudcli", "pudlib", "puds", "pudw"]

[workspace.dependencies]
actix = "0.13.5"
actix-codec = "0.5.2"
actix-http = "3.9.0"
actix-rt = "2.10.0"
anyhow = "1.0.93"
awc = { version = "3.5.1", default-features = false, features = [
    "compress-brotli",
    "rustls-0_23",
] }
bincode = "1.3.3"
bytes = "1.8.0"
clap = { version = "4.5.20", features = ["derive"] }
futures = "0.3.31"
getset = "0.1.3"
lazy_static = "1.5.0"
regex = "1.11.1"
rustversion = "1.0.18"
serde = { version = "1.0.214", features = ["derive"] }
thiserror = "2.0.3"
time = "0.3.36"
tokio = { version = "1.41.1", features = ["sync"] }
tracing = { version = "0.1.40", features = [
  "max_level_trace",
  "release_max_level_info",
] }
typed-builder = "0.20.0"
uuid = { version = "1.11.0", features = ["v4", "serde"] }
vergen-gix = { version = "1.0.2", features = [
  "build",
  "cargo",
  "rustc",
  "si",
] }
