[workspace]
resolver = "2"

members = ["pudcli", "pudlib", "puds", "pudw"]

[workspace.dependencies]
actix = "0.13.5"
actix-codec = "0.5.2"
actix-http = "3.9.0"
actix-rt = "2.10.0"
anyhow = "1.0.94"
awc = { version = "3.5.1", features = ["rustls-0_22-webpki-roots"] }
bincode = "1.3.3"
bytes = "1.9.0"
clap = { version = "4.5.23", features = ["derive"] }
futures = "0.3.31"
getset = "0.1.3"
lazy_static = "1.5.0"
regex = "1.11.1"
rustversion = "1.0.18"
serde = { version = "1.0.216", features = ["derive"] }
thiserror = "2.0.8"
time = "0.3.37"
tokio = { version = "1.42.0", features = ["sync"] }
tracing = { version = "0.1.41", features = [
  "max_level_trace",
  "release_max_level_info",
] }
typed-builder = "0.20.0"
uuid = { version = "1.16.0", features = ["v4", "serde"] }
vergen-gix = { version = "1.0.3", features = ["build", "cargo", "rustc", "si"] }
