[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
categories = ["web-programming::websocket", "web-programming"]
description = "Websocket based job scheduling system"
documentation = "https://docs.rs/puds"
edition = "2021"
homepage = "https://github.com/rustyhorde/pud"
keywords = ["job", "scheduling", "websocket", "actix"]
license = "MIT OR Apache-2.0"
name = "pudw"
readme = "README.md"
repository = "https://github.com/rustyhorde/pud"
resolver = "2"
version = "0.1.0"

[features]
unstable = []

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
getset = "0.1.2"
pudlib = { path = "../pudlib" }
serde = { version = "1.0.149", features = ["derive"] }
thiserror = "1.0.37"
tracing = { version = "0.1.37", features = ["max_level_trace", "release_max_level_trace"] }

[build-dependencies]
rustversion = "1.0.9"

[dev-dependencies]
lazy_static = "1.4.0"