[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
categories = ["web-programming::websocket", "web-programming"]
description = "Websocket based job scheduling system"
documentation = "https://docs.rs/puds"
edition = "2021"
homepage = "https://github.com/rustyhorde/pud"
keywords = ["job", "scheduling", "websocket", "actix"]
license = "MIT OR Apache-2.0"
name = "puds"
readme = "README.md"
repository = "https://github.com/rustyhorde/pud"
resolver = "2"
version = "0.1.0"

[dependencies]
actix = "0.13.0"
actix-http = "3.3.0"
actix-web = { version = "4.3.0", default-features = false, features = [
    "compress-brotli",
    "macros",
    "rustls",
] }
actix-web-actors = "4.2.0"
anyhow = "1.0.69"
bincode = "1.3.3"
bytestring = "1.2.0"
clap = { version = "4.1.4", features = ["derive"] }
getset = "0.1.2"
pudlib = { path = "../pudlib" }
ruarango = "0.1.2"
rustls = "0.20.8"
rustls-pemfile = "1.0.2"
serde = { version = "1.0.153", features = ["derive"] }
thiserror = "1.0.38"
time = { version = "0.3.17", features = ["serde", "serde-human-readable"] }
tracing = { version = "0.1.37", features = ["max_level_trace", "release_max_level_info"] }
typed-builder = "0.12.0"
uuid = { version = "1.3.0", features = ["v4", "serde"] }

[build-dependencies]
anyhow = "1.0.69"
rustversion = "1.0.11"
vergen = { version = "8.0.0-beta.5", features = [
    "build",
    "cargo",
    "git",
    "gitoxide",
    "rustc",
    "si",
] }

[dev-dependencies]
actix-rt = "2.8.0"
lazy_static = "1.4.0"
