[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
categories = ["web-programming::websocket", "web-programming"]
description = "Websocket based job scheduling system"
documentation = "https://docs.rs/puds"
edition = "2021"
homepage = "https://github.com/rustyhorde/pud"
keywords = ["job", "scheduling", "websocket", "actix"]
license = "MIT OR Apache-2.0"
name = "puds"
readme = "README.md"
repository = "https://github.com/rustyhorde/pub"
resolver = "2"
version = "0.1.0"

[dependencies]
actix-web = { version = "4.2.1", features = ["rustls"] }
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
console = "0.15.2"
const_format = "0.2.30"
dirs2 = "3.0.1"
getset = "0.1.2"
indexmap = "1.9.2"
lazy_static = "1.4.0"
rand = "0.8.5"
serde = { version = "1.0.148", features = ["derive"] }
thiserror = "1.0.37"
tokio = { version = "1.22.0", features = ["macros"] }
toml = "0.5.9"
tracing = { version = "0.1.37", features = ["max_level_trace", "release_max_level_warn"] }
tracing-subscriber = { version = "0.3.16", features = ["time"] }

[build-dependencies]
anyhow = "1.0.66"
rustversion = "1.0.9"
vergen = "7.4.3"

[dev-dependencies]
lazy_static = "1.4.0"
regex = "1.7.0"
