[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
categories = ["web-programming::websocket", "web-programming"]
description = "Websocket based job scheduling system"
documentation = "https://docs.rs/puds"
edition = "2021"
homepage = "https://github.com/rustyhorde/pud"
keywords = ["job", "scheduling", "websocket", "actix"]
license = "MIT OR Apache-2.0"
name = "puds"
readme = "README.md"
repository = "https://github.com/rustyhorde/pud"
resolver = "2"
version = "0.1.0"

[dependencies]
actix = "0.13.0"
actix-http = "3.2.2"
actix-web = { version = "4.2.1", features = ["rustls"] }
actix-web-actors = "4.1.0"
anyhow = "1.0.66"
bincode = "1.3.3"
bytestring = "1.2.0"
clap = { version = "4.0.29", features = ["derive"] }
getset = "0.1.2"
pudlib = { path = "../pudlib" }
ruarango = "0.1.0"
rustls = "0.20.7"
rustls-pemfile = "1.0.1"
serde = { version = "1.0.148", features = ["derive"] }
thiserror = "1.0.37"
time = { version = "0.3.17", features = ["serde", "serde-human-readable"] }
toml = "0.5.9"
tracing = { version = "0.1.37", features = ["max_level_trace", "release_max_level_info"] }
typed-builder = "0.11.0"
uuid = { version = "1.2.2", features = ["v4", "serde"] }

[build-dependencies]
anyhow = "1.0.66"
rustversion = "1.0.9"
vergen = { version = "8.0.0-beta.0", features = [
    "build",
    "cargo",
    "git",
    "gix",
    "rustc",
    "si",
] }

[dev-dependencies]
actix-rt = "2.7.0"
lazy_static = "1.4.0"
