[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
categories = ["web-programming::websocket", "web-programming"]
description = "Websocket based job scheduling system"
documentation = "https://docs.rs/pudlib"
edition = "2021"
homepage = "https://github.com/rustyhorde/pud"
keywords = ["job", "scheduling", "websocket", "actix"]
license = "MIT OR Apache-2.0"
name = "pudlib"
readme = "README.md"
repository = "https://github.com/rustyhorde/pud"
resolver = "2"
version = "0.1.0"

[features]
unstable = []

[dependencies]
actix = "0.13.0"
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
console = "0.15.2"
const_format = "0.2.30"
dirs2 = "3.0.1"
getset = "0.1.2"
indexmap = "1.9.2"
lazy_static = "1.4.0"
rand = "0.8.5"
serde = { version = "1.0.149", features = ["derive"] }
thiserror = "1.0.37"
time = { version = "0.3.17", features = ["formatting"] }
toml = "0.5.9"
tracing = { version = "0.1.37", features = ["max_level_trace", "release_max_level_trace"] }
tracing-subscriber = { version = "0.3.16", features = ["time"] }

[build-dependencies]
anyhow = "1.0.66"
rustversion = "1.0.9"
vergen = "7.4.3"

[dev-dependencies]
anyhow = "1.0.66"
regex = "1.7.0"
